// frontend/src/components/Login.tsx
import type { FormEvent } from "react";
import { useState } from "react";
import { login } from "../lib/auth";

interface LoginProps {
  onSuccess: () => void;
  onSwitchToRegister?: () => void;
}

export function Login({ onSuccess }: LoginProps) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      await login(email, password);
      onSuccess();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Login failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-card">
      <h2>Sign In</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="login-email">Email</label>
          <input
            id="login-email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            autoComplete="email"
            placeholder="you@example.com"
          />
        </div>
        <div className="form-group">
          <label htmlFor="login-password">Password</label>
          <input
            id="login-password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            autoComplete="current-password"
            placeholder="••••••••"
          />
        </div>
        {error && <div className="error-message">{error}</div>}
        <button type="submit" className="btn btn-primary" disabled={loading}>
          {loading ? "Signing in..." : "Sign In"}
        </button>
      </form>
    </div>
  );
}

// frontend/pages/login.vue
<script setup lang="ts">
definePageMeta({
  layout: "auth",
});

const router = useRouter();
const auth = useAuthStore();
const mail = useMailStore();

const form = reactive({
  email: "",
  password: "",
});

const submitting = ref(false);
const errorMessage = ref("");

async function handleSubmit() {
  submitting.value = true;
  errorMessage.value = "";
  try {
    await auth.login({ ...form });
    await mail.bootstrap();
    await router.push("/");
  } catch (error) {
    errorMessage.value =
      (error as { data?: { error?: string }; message?: string }).data?.error ??
      (error as Error).message ??
      "Unable to login";
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <form class="space-y-6" @submit.prevent="handleSubmit">
    <div class="space-y-2 text-center">
      <p class="text-sm font-medium uppercase tracking-[0.3em] text-brand-400">Free Mail</p>
      <h1 class="text-2xl font-semibold">Welcome back</h1>
      <p class="text-sm text-slate-400">Sign in to manage your inboxes and domains.</p>
    </div>

    <div class="space-y-4">
      <div>
        <label for="email" class="text-sm font-medium text-slate-300">Email</label>
        <input
          id="email"
          v-model="form.email"
          type="email"
          required
          autocomplete="username"
          placeholder="admin@yourdomain.com"
          class="mt-2 w-full rounded-xl border border-slate-700 bg-slate-900/50 px-4 py-3 text-slate-100 placeholder-slate-500 focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-400/40"
        />
      </div>

      <div>
        <label for="password" class="text-sm font-medium text-slate-300">Password</label>
        <input
          id="password"
          v-model="form.password"
          type="password"
          required
          autocomplete="current-password"
          placeholder="••••••••"
          class="mt-2 w-full rounded-xl border border-slate-700 bg-slate-900/50 px-4 py-3 text-slate-100 placeholder-slate-500 focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-400/40"
        />
      </div>
    </div>

    <p v-if="errorMessage" class="text-sm text-rose-400">
      {{ errorMessage }}
    </p>

    <button
      type="submit"
      :disabled="submitting"
      class="w-full rounded-xl bg-brand-500 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-brand-500/30 transition hover:bg-brand-400 disabled:cursor-not-allowed disabled:opacity-60"
    >
      <span v-if="!submitting">Sign in</span>
      <span v-else>Signing you in…</span>
    </button>
  </form>
</template>
